Less8/geekshop/authapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp

from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

Less8/geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
]

Less8/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('products/', mainapp.products, name='products'),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('social/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Less8/geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

Less8/geekshop/mainapp/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

Less8/geekshop/mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def main(request):
    return render(request, 'mainapp/index.html',)


def products(request):
    return render(request, 'mainapp/products.html')


def contact(request):
    return render(request, 'mainapp/contact.html')


from .models import ProductCategory, Product


def main(request):
    title = 'главная'

    products = Product.objects.all()[:4]

    content = {'title': title, 'products': products}
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    print(pk)

    title = 'продукты'
    links_menu = ProductCategory.objects.all()

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products,
        }

        return render(request, 'mainapp/products_list.html', content)

    same_products = Product.objects.all()[3:5]

    content = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products
    }

    return render(request, 'mainapp/products.html', content)


basket = []
if request.user.is_authenticated:
    basket = Basket.objects.filter(user=request.user)

if pk:
    if pk == '0':
        products = Product.objects.all().order_by('price')
        category = {'name': 'все'}
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = Product.objects.filter(category__pk=pk).order_by('price')

    content = {
        'title': title,
        'links_menu': links_menu,
        'category': category,
        'products': products,
        'basket': basket,
    }

    return render(request, 'mainapp/products_list.html', content)



def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk)[:3]

    return same_products


...


def products(request, pk=None):
    title = 'продукты'
    links_menu = ProductCategory.objects.all()
    basket = get_basket(request.user)

    ...

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }

    return render(request, 'mainapp/products.html', content)


def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)
    basket = getBasket(request.user)

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, \
                                              category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, \
                                              is_active=True, category__is_active=True).order_by('price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'basket': basket,
        }

        return render(request, 'mainapp/products_list.html', content)

Less8/geekshop/mainapp/templates/mainapp/BASE.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
   <!-- <link rel="stylesheet" href="style.css"> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">
    {% block css %}
    {% endblock %}
</head>

<body>
    <div class="container">
        <div class="slider padding-site">
            <div class="header">
                <a class="logo" href="#"><img src="/static/img/logo.svg" alt="logo"></a>
                {% block menu %}
                {% endblock %}

            </div>
            <div class="slider-text">
                <h4 class="slider-h4">TRENDING</h4>
                <h2 class="slider-h2">Fishnet Chair</h2>
                <p class="slider-p">
                    Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black
                </p>
                <a href="#" class="button">order us</a>
            </div>
            <div class="slider-pagination">
                <a href="#" class="circle"></a>
                <a href="#" class="circle circle-active"></a>
                <a href="#" class="circle"></a>
            </div>
        </div>

        <div class="block-1 padding-site">
            <div class="block-head">
                <ul class="menu-1">
                    <li><a href="#" class="menu-link-active menu-link">Featured </a></li>
                    <li><a href="#" class="menu-link">New</a></li>
                </ul>
                <a href="#" class="block-head-explore">explore all &gt;</a>
            </div>
            <div class="marg">
                <div class="area-1">
                    <a href="#" class="button-circle"><img class="arrow" src="/static/img/arrow.jpg" alt=""></a>
                    <p class="text-banner">Fishnet Chair</p>
                    <p class="block-1-p">Seat and back with upholstery made of cold cure foamk</p>
                </div>


                <div class="area">
                    <a href="#"> <img src="/static/img\product-2.png" alt="product-2"></a>
                </div>
                <div class="area">
                    <a href="#"> <img src="/static/img\product-3.png" alt="product-3"></a>
                </div>
                <div class="area">
                    <a href="#"> <img src="/static/img\product-4.png" alt="product-4"></a>
                </div>

            </div>
        </div>
        <div class="block">
            <div class="block-left">
                <div class="block-padding">
                    <h1 class="text-exc">exclusive</h1>
                    <h2 class="text-prod">Fishnet Chair</h2>
                    <h3 class="text-ob">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</h3>
                    <a href="#" class="button">order us</a>
                </div>
            </div>
            <div class="block-right">
                <div class="block-padding">
                    <h1 class="text-exc">exclusive</h1>
                    <h2 class="text-prod">Fishnet Chair</h2>
                    <h3 class="text-ob">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</h3>
                    <a href="#" class="button">order us</a>
                </div>
            </div>
        </div>
        <div class="block-2 padding-site">
            <div class="block-head">
                <p class="menu-2">Trending Products</p>
                <a href="#" class="block-head-explore-2">explore all &gt;</a>
            </div>
            <div class="prod-photo">
                <div><img class="image" src="/static/img/product-11.jpg" alt="">
                </div>
                <div><img class="image" src="/static/img/product-21.jpg" alt=""></div>
                <div><img class="image" src="/static/img/product-31.jpg" alt=""></div>
                <div><img class="image" src="/static/img/product-41.jpg" alt=""></div>
                <div> <img class="image" src="/static/img/product-5.jpg" alt=""></div>
                <div><img class="image" src="/static/img/product-6.jpg" alt=""></div>
            </div>
        </div>
        <div class="slider padding-site" style="background-image: url(img/slider.png); margin-top: 120px">
            <div class="slider-text" style="margin-top: 287px">
                <h4 class="slider-h4" style="color: #e53935">Hot deal</h4>
                <h2 class="slider-h2">Fishnet Chair</h2>
                <p class="slider-p">
                    SSeat and back with upholstery made of cold cure foam. Steel frame,
                </p>
                <a href="#" class="button">order us</a>
            </div>
            <div class="slider-pagination">
                <a href="" class="circle"></a>
                <a href="" class="circle circle-active"></a>
                <a href="" class="circle"></a>
            </div>
        </div>
        <div class="block-prod padding-site">
            <div class="block-left-1">
                <div class="block-padding">
                    <h1 class="text-exc">exclusive</h1>
                    <h2 class="text-prod">Fishnet Chair</h2>
                    <h3 class="text-ob">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</h3>
                    <a href="#" class="button">order us</a>
                </div>
            </div>
            <div class="block-right-1">
                <div><img class="image" src="/static/img/product-2-sm.png" alt="">
                </div>
                <div><img class="image" src="/static/img/product-3-sm.png" alt=""></div>
                <div><img class="image" src="/static/img/product-4-sm.png" alt=""></div>
                <div><img class="image" src="/static/img/product-5-sm.png" alt=""></div>
            </div>
        </div>

        <div class="mobile padding-site" style="background-image: url(img/back-img.png)">
            <div class="mobile-text">
                <p class="slider-h4" style="color: #6c6c6c;">mobile app</p>
                <p class="slider-h2">Find. Follow. Favorite</p>
                <p class="slider-p">Save your favorites and share your style.</p>
                <a href="#"><img src="/static/img/google-play.png" alt="google"></a>
                <a href="#"><img src="/static/img/app-store.png" alt=""></a>
            </div>
        </div>

  <div class="footer padding-site">
            <div class="contact_us">
                <p class="footer-h2">contact us</p>
                <p class="footer_p">132A Bridge Road Richmond VIC Australia.</p>
                <p class="footer_p">Talk to us on 1300 132
                    info@interior.com</p>
            </div>
            <div class="user-inf">
                <p class="footer-h2">Useful Information</p>
                <div class="colums">
                    <p class="footer-pB">Sales terms Customer care Delivery</p>
                    <p class="footer-pB2">Architect accounts <br> Careers <br> Exchanges &amp; returns</p>
                </div>
            </div>
            <div class="stay">
                <p class="footer-h2">Let’s Stay in Touch!</p>
                <p class="footer-p1">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                <p><input class="emeil" type="email" placeholder="   your email address" alt="emeil"></p>
            </div>

            <div class="footer_bottom">


                    <p class="bottom-p">&copy;&nbsp;Copyright&nbsp;&mdash; INTERIOR 2016. All Rights Reserved.</p>


                    <p><img src="/static/img/social-links.png" alt=""></p>

                    <p>Terms &amp;&nbsp;Conditions&nbsp;/ Privacy policy &amp;&nbsp;Cookies</p>
{% block content %}
    {% endblock %}

            </div>
        </div>
    </div>

</body>

</html>

Less8/geekshop/mainapp/templates/mainapp/contacts.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Контакты</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
    <!-- <link rel="stylesheet" href="style.css"> -->
   <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">
</head>
</head>

<body>
    <div class="container">
        <div class="slider-contacts padding-site">
            <div class="header">
                <a class="logo" href="index.html"><img src="img/logo.svg" alt="logo"></a>
                <ul class="menu">
                    <li><a href="index.html" class="menu-link-active menu-link">HOME </a></li>
                    <li><a href="products.html" class="menu-link">PRODUCTS </a></li>
                    <li><a href="#" class="menu-link">HISTORY </a></li>
                    <li><a href="#" class="menu-link">SHOWROOM</a></li>
                    <li><a href="contacts.html" class="menu-link">CONTACT</a></li>
                    <li><a href="#" class="menu-link"><img src="img/search.svg" alt="search"></a></li>
                </ul>
            </div>
            <div class="slider-text-contacts">            
                <h2 class="slider-h2-contacts">Contact Us</h2>
            </div>
        </div>

        <div class="block-1-contacts padding-site">

            <div class="marg">
                <div class="area-1-contacts">
                    <img src="img/cursor.jpg" alt="">
                    <p class="text-banner">California</p>
                    <div class="contacts">
                        <p class="phone">Phone:</p>
                        <p class="numbers"> 1900 - 1234 -5678</p>
                        <p>Email:</p>
                        <p class="numbers"> info@interior.com</p>
                        <p class="phone"> Address:</p>
                        <p class="address"> 12 W 1st St, 90001 Los Angeles, California</p>
                    </div>
                </div>
                <div class="area-1-contacts">
                    <img src="img/cursor.jpg" alt="">
                    <p class="text-banner">California</p>
                    <div class="contacts">
                        <p class="phone">Phone:</p>
                        <p class="numbers"> 1900 - 1234 -5678</p>
                        <p>Email:</p>
                        <p> info@interior.com</p>
                        <p> Address:</p>
                        <p class="address"> 12 W 1st St, 90001 Los Angeles, California</p>
                    </div>
                </div>
                <div class="area-1-contacts">
                    <img src="img/cursor.jpg" alt="">
                    <p class="text-banner">California</p>
                    <div class="contacts">
                        <p class="phone">Phone:</p>
                        <p class="numbers"> 1900 - 1234 -5678</p>
                        <p>Email:</p>
                        <p> info@interior.com</p>
                        <p> Address:</p>
                        <p class="address"> 12 W 1st St, 90001 Los Angeles, California</p>
                    </div>
                </div>

            </div>
        </div>

        <div class="footer padding-site">
            <div class="contact_us">
                <p class="footer-h2">contact us</p>
                <p class="footer_p">132A Bridge Road Richmond VIC Australia.</p>
                <p class="footer_p">Talk to us on 1300 132
                    info@interior.com</p>
            </div>
            <div class="user-inf">
                <p class="footer-h2">Useful Information</p>
                <div class="colums">
                    <p class="footer-pB">Sales terms Customer care Delivery</p>
                    <p class="footer-pB2">Architect accounts <br> Careers <br> Exchanges &amp; returns</p>
                </div>
            </div>
            <div class="stay">
                <p class="footer-h2">Let’s Stay in Touch!</p>
                <p class="footer-p1">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                <p><input class="emeil" type="email" placeholder="   your email address" alt="emeil"></p>
            </div>

            <div class="footer_bottom">


                <p class="bottom-p">&copy;&nbsp;Copyright&nbsp;&mdash; INTERIOR 2016. All Rights Reserved.</p>


                <p><img src="img/social-links.png" alt=""></p>

                <p>Terms &amp;&nbsp;Conditions&nbsp;/ Privacy policy &amp;&nbsp;Cookies</p>


            </div>
        </div>
    </div>

</body>

</html>

Less8/geekshop/mainapp/templates/mainapp/product-deals.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <div class="container">
        <div class="slider-contacts-prod padding-site">
            <div class="header">
                <a class="logo" href="index.html"><img src="img/logo.svg" alt="logo"></a>
                <ul class="menu">
                    <li><a href="index.html" class="menu-link-active menu-link">HOME </a></li>
                    <li><a href="products.html" class="menu-link">PRODUCTS </a></li>
                    <li><a href="#" class="menu-link">HISTORY </a></li>
                    <li><a href="product-deals.html" class="menu-link">SHOWROOM</a></li>
                    <li><a href="contacts.html" class="menu-link">CONTACT</a></li>
                    <li><a href="#" class="menu-link"><img src="img/search.svg" alt="search"></a></li>
                </ul>
            </div>
            <div class="slider-text-contacts">
                <h2 class="slider-h2-contacts">Our Products Range</h2>
            </div>
        </div>
        <div class="main-menu-prod padding-site">
            <ul class="menu-head">
                <li class="menu-link-all">All</li>
                <li class="menu-link-head"> HOME</li>
                <li class="menu-link-head">OFFICE </li>
                <li class="menu-link-head">FURNITURE </li>
                <li class="menu-link-head">MODERN</li>
                <li class="menu-link-head">CLASSIC</li>
            </ul>
        </div>

        <div class="marg-prod padding-site">
            <div class="area-prod">
                <a href="#"> <img src="img\product-11.png" alt="product-11"></a>
            </div>
            <div class="area-prod">
                <a href="#"> <img src="img\product-21.jpg" alt="product-21"></a>
            </div>
            <div class="area-prod">
                <a href="#"> <img src="img\product-31.jpg" alt="product-31"></a>
            </div>
            <div class="area-prod">
                <a href="#"> <img src="img\product-41.jpg" alt="product-41"></a>
            </div>
            <div class="area-prod">
                <a href="#"> <img src="img\product-5.jpg" alt="product-5"></a>
            </div>
            <div class="area-prod">
                <a href="#"> <img src="img\product-61.jpg" alt="product-6"></a>
            </div>
            <div class="area-prod">
                <a href="#"> <img src="img\product-11.jpg" alt="product-11"></a>
            </div>
            <div class="area-prod">
                <a href="#"> <img src="img\product-21.jpg" alt="product-21"></a>
            </div>
            <div class="area-prod">
                <a href="#"> <img src="img\product-31.jpg" alt="product-31"></a>
            </div>
        </div>
        <div class="circle-arrow">
            <img src="img/circle-arrow.jpg" alt="circle-arrow.">
        </div>




        <div class="block">
            <div class="block-left">
                <div class="block-padding">
                    <h1 class="text-exc">exclusive</h1>
                    <h2 class="text-prod">Fishnet Chair</h2>
                    <h3 class="text-ob">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</h3>
                    <a href="#" class="button">order us</a>
                </div>
            </div>
            <div class="block-right">
                <div class="block-padding">
                    <h1 class="text-exc">exclusive</h1>
                    <h2 class="text-prod">Fishnet Chair</h2>
                    <h3 class="text-ob">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</h3>
                    <a href="#" class="button">order us</a>
                </div>
            </div>
        </div>


        <div class="footer padding-site">
            <div class="contact_us">
                <p class="footer-h2">contact us</p>
                <p class="footer_p">132A Bridge Road Richmond VIC Australia.</p>
                <p class="footer_p">Talk to us on 1300 132
                    info@interior.com</p>
            </div>
            <div class="user-inf">
                <p class="footer-h2">Useful Information</p>
                <div class="colums">
                    <p class="footer-pB">Sales terms Customer care Delivery</p>
                    <p class="footer-pB2">Architect accounts <br> Careers <br> Exchanges &amp; returns</p>
                </div>
            </div>
            <div class="stay">
                <p class="footer-h2">Let’s Stay in Touch!</p>
                <p class="footer-p1">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                <p><input class="emeil" type="email" placeholder="   your email address" alt="emeil"></p>
            </div>

            <div class="footer_bottom">


                <p class="bottom-p">&copy;&nbsp;Copyright&nbsp;&mdash; INTERIOR 2016. All Rights Reserved.</p>


                <p><img src="img/social-links.png" alt=""></p>

                <p>Terms &amp;&nbsp;Conditions&nbsp;/ Privacy policy &amp;&nbsp;Cookies</p>


            </div>
        </div>
    </div>
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}"
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>

</body>

</html>

Less8/geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}
  <div class="hero-white">
    <div class="header clearfix">
      {% include 'mainapp/includes/inc_menu.html' %}
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
      <div class="title clearfix">
        <h2>
          Категория: "{{ category.name|title }}"
        </h2>
      </div>
      <div class="category-products clearfix">

        {% for product in products %}
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="product">
              <div class="text">
                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                  <h4>{{ product.name }}</h4>
                  <p>{{ product.description }}</p>
              </div>
            </a>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>

  <div class="clr"></div>

{% endblock %}
<div class="category-products clearfix">
  {% for product in products %}
    <div class="block">
      <a href="{% url 'basket:add' product.pk %}">
        <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
        <div class="text">
          <img src="{% static 'img/icon-hover.png' %}" alt="hover">
          <h4>{{ product.name }}</h4>
          <p>{{ product.description }} </p>
        </div>
      </a>
    </div>
  {% endfor %}
</div>
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
      <div class="title clearfix">
        <h2>Категория: "{{ category.name|title }}"</h2>
        <div class="paginator">
          {% if products.has_previous %}
            <a href="{% url 'products:page'
                             category.pk products.previous_page_number %}">
              <
            </a>
          {% endif %}
          <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
          {% if products.has_next %}
            <a href="{% url 'products:page'
                             category.pk products.next_page_number %}">
              >
            </a>
          {% endif %}
        </div>
      </div>
      <div class="category-products clearfix">
        {% for product in products %}